---
- name: Variaveis no ansible
  hosts: all
  vars:
  - username: agile
  tasks:
  - user:
      name: '{{username}}'
      shell: /bin/bash
      createhome: yes
      state: absent
    become: yes
...
