- name: Provisionando um Servidor Web
  hosts: minion
  become: yes
  tasks:
  - package:
      name: apache2
      state: present
  - file:
      path: /var/www/html/infra-agil
      state: directory
  - unarchive:
      src: /root/playbooks/files/site.tar.gz
      dest: /var/www/html/infra-agil
  - service:
      name: apache2
      state: started
      enabled: yes
